version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  globoticket.ticketmanagement.api:
    image: ${DOCKER_REGISTRY-}globoticketticketmanagementapi
    build:
      context: .
      dockerfile: src/API/GloboTicket.TicketManagement.Api/Dockerfile

  #globoticket.ticketmanagement.api.integrationtests:
  #  image: ${DOCKER_REGISTRY-}globoticketticketmanagementapiintegrationtests
  #  build:
  #    context: .
  #    dockerfile: test/GloboTicket.TicketManagement.API.IntegrationTests/Dockerfile



  #globoticket.ticketmanagement.api.integrationtests:
  #  image: ${DOCKER_REGISTRY-}globoticketticketmanagementapiintegrationtests
  #  build:
  #    context: .
  #    dockerfile: test/GloboTicket.TicketManagement.API.IntegrationTests/Dockerfile

