name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      
      - name: Setup .NET 3.1 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Start SQL Server
        run: |
          docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
          
      - name: Sleep for 5 seconds 😴
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Restore dependencies 🛠
        run: dotnet restore
      
      - name: Build app 🚀
        run: dotnet build -c Release --no-restore

      - name: Run automated tests 🧪
        env:
          ConnectionStrings__DefaultConnection: Server=localhost;Database=CiCdDemo_Test;User=sa;Password=2@LaiNw)PDvs^t>L!Ybt]6H^%h3U>M
        run: dotnet test -c Release --no-build


