name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./src
        run: docker-compose up --exit-code-from docker-compose up --exit-code-from integration-tests integration-tests
